name: Build and Push Packages

on:
  schedule:
    - cron: "0 12 * * 5" # Run every Friday at 12:00 PM UTC

jobs:
  build_and_push:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: make all
        run: make uipath
